### ISSUE TITLE
Favicons not very visible

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/OE-System#2]
The icons curently intended for use on each sub-system aren't particularly visible in the browser tabs:
![tab](https://cloud.githubusercontent.com/assets/9369383/25627439/7faeff32-2f5a-11e7-8caa-77fae61d7ac5.png)

I think changing them from black to the appropriate team colour (pink, blue, orange etc.) would work better.

Alternatively, we could use the same coloured ring icon across all pages:
![image 3](https://cloud.githubusercontent.com/assets/9369383/26116881/94fbbd82-3a5c-11e7-8725-cdb8e2d390e9.png)

**Comment by Jarlaxle1979** [comment]
Favicon changed on all sites to main provide icon
