### ISSUE TITLE
Tickets: Blacklist management

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/OE-System#22]
The ticket creator python code is set to not send any automatic replies to messages from blacklisted addresses. These addresses are stored in the blacklist table of the database, but there's currently no way to view, remove or add to this list from the front-end.

Sadly it's not as simple as adding an email address via a text box as Outlook records internal emails as a long code, rather than the actual email address. Solution: A search function on SENDER_NAME that returns their address code.

**Comment by Jarlaxle1979** [comment]
Page created and new css applied.

Height of result container not applying - needs to be fixed
Also needs to be linked from the NAV
